import { appSchema, tableSchema } from '@nozbe/watermelondb'

// WatermelonDB schema v1 — offline-first, client-generated UUID per §2 (Primary key strategy)
// All syncable Postgres tables mirrored; sync_version stays server-side but cached locally for conflict check (§4)
// Watermelon auto-adds id, created_at, updated_at; we add deleted_at soft-delete + business_id + sync_version
export const schema = appSchema({
  version: 3,
  tables: [
    tableSchema({
      name: 'products',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'sku', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'tax_rule_id', type: 'string', isOptional: true },
        { name: 'price', type: 'string' },
        { name: 'cost', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'product_variants',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'sku', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'price', type: 'string' },
        { name: 'cost', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'tags', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'loyalty_points', type: 'number' },
        { name: 'total_spend', type: 'string' },
        { name: 'last_purchase_at', type: 'number', isOptional: true },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'inventory_items',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'quantity', type: 'string' },
        { name: 'low_stock_threshold', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'stock_movements',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'quantity_delta', type: 'string' },
        { name: 'movement_type', type: 'string' },
        { name: 'reference_type', type: 'string', isOptional: true },
        { name: 'reference_id', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'occurred_at', type: 'number' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'subtotal', type: 'string' },
        { name: 'tax_amount', type: 'string' },
        { name: 'total', type: 'string' },
        { name: 'payment_method', type: 'string' },
        { name: 'idempotency_key', type: 'string', isOptional: true },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'order_lines',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        {
          name: 'product_variant_id',
          type: 'string',
          isOptional: true,
        },
        { name: 'quantity', type: 'string' },
        { name: 'unit_price', type: 'string' },
        { name: 'line_total', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'sales',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'order_id', type: 'string', isOptional: true },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'receipt_number', type: 'string' },
        { name: 'staff_id', type: 'string' },
        { name: 'payment_method', type: 'string' },
        { name: 'subtotal', type: 'string' },
        { name: 'tax_amount', type: 'string' },
        { name: 'total', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'sold_at', type: 'number' },
        { name: 'idempotency_key', type: 'string', isOptional: true },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'sale_lines',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'sale_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        {
          name: 'product_variant_id',
          type: 'string',
          isOptional: true,
        },
        { name: 'quantity', type: 'string' },
        { name: 'unit_price', type: 'string' },
        { name: 'line_total', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'expenses',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'category', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'vendor', type: 'string', isOptional: true },
        { name: 'amount', type: 'string' },
        { name: 'tax_amount', type: 'string' },
        { name: 'is_recurring', type: 'boolean' },
        { name: 'recurring_interval', type: 'string', isOptional: true },
        { name: 'spent_at', type: 'number' },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'invoices',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'invoice_number', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'subtotal', type: 'string' },
        { name: 'tax_amount', type: 'string' },
        { name: 'total', type: 'string' },
        { name: 'amount_paid', type: 'string' },
        { name: 'amount_due', type: 'string' },
        { name: 'currency', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'due_at', type: 'number', isOptional: true },
        { name: 'sent_at', type: 'number', isOptional: true },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'invoice_lines',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isOptional: true },
        { name: 'description', type: 'string' },
        { name: 'quantity', type: 'string' },
        { name: 'unit_price', type: 'string' },
        { name: 'line_total', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'payment_commands',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'string' },
        { name: 'currency', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'provider', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    // legacy alias kept for migration from old installs that used `payments`
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'invoice_id', type: 'string', isOptional: true },
        { name: 'order_id', type: 'string', isOptional: true },
        { name: 'amount', type: 'string' },
        { name: 'currency', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'provider', type: 'string' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'tax_rules',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'rate', type: 'string' },
        { name: 'country', type: 'string' },
        { name: 'is_default', type: 'boolean' },
        { name: 'is_active', type: 'boolean' },
        { name: 'sync_version', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    // Sync metadata + conflicts cache (local copy of server conflicts for UI)
    tableSchema({
      name: 'conflicts',
      columns: [
        { name: 'business_id', type: 'string', isIndexed: true },
        { name: 'table_name', type: 'string' },
        { name: 'record_id', type: 'string', isIndexed: true },
        { name: 'client_payload', type: 'string' },
        { name: 'server_payload', type: 'string' },
        { name: 'client_version', type: 'number' },
        { name: 'server_version', type: 'number' },
        { name: 'resolution', type: 'string', isOptional: true },
      ],
    }),
  ],
})
