DROP TABLE IF EXISTS conflicts;
ALTER TABLE tax_rules DROP COLUMN IF EXISTS sync_version;
ALTER TABLE payment_commands DROP COLUMN IF EXISTS sync_version;
ALTER TABLE payments DROP COLUMN IF EXISTS sync_version;
ALTER TABLE invoice_lines DROP COLUMN IF EXISTS sync_version;
ALTER TABLE invoices DROP COLUMN IF EXISTS sync_version;
ALTER TABLE expenses DROP COLUMN IF EXISTS sync_version;
ALTER TABLE sale_lines DROP COLUMN IF EXISTS sync_version;
ALTER TABLE sales DROP COLUMN IF EXISTS sync_version;
ALTER TABLE order_lines DROP COLUMN IF EXISTS sync_version;
ALTER TABLE orders DROP COLUMN IF EXISTS sync_version;
ALTER TABLE stock_movements DROP COLUMN IF EXISTS sync_version;
ALTER TABLE inventory_items DROP COLUMN IF EXISTS sync_version;
ALTER TABLE customers DROP COLUMN IF EXISTS sync_version;
ALTER TABLE product_variants DROP COLUMN IF EXISTS sync_version;
ALTER TABLE products DROP COLUMN IF EXISTS sync_version;
DROP INDEX IF EXISTS idx_products_sync_version;
DROP INDEX IF EXISTS idx_customers_sync_version;
DROP INDEX IF EXISTS idx_orders_sync_version;
DROP INDEX IF EXISTS idx_expenses_sync_version;
DROP INDEX IF EXISTS idx_invoices_sync_version;
